### ISSUE TITLE
Calling tesseract from ruby app gives "sh: tesseract: not found"

### ISSUE THREAD

**Issue by wrumble** [tesseract-shadow/tesseract-ocr-compilation#1]
After using an adapted version of the docker file provided in this repo that adds my app. When i call tesseract from my ruby app i get `sh: tesseract: not found`. My Dockerfile looks like this and installs fine:

`   FROM ubuntu:16.04

    RUN apt-get update && apt-get install -y \
        autoconf \
        autoconf-archive \
        automake \
        build-essential \
        checkinstall \
        cmake \
        g++ \
        git \
        libcairo2-dev \
        libcairo2-dev \
        libicu-dev \
        libicu-dev \
        libjpeg8-dev \
        libjpeg8-dev \
        libpango1.0-dev \
        libpango1.0-dev \
        libpng12-dev \
        libpng12-dev \
        libtiff5-dev \
        libtiff5-dev \
        libtool \
        pkg-config \
        wget \
        xzgv \
        zlib1g-dev

    # SSH for diagnostic
    RUN apt-get update && apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages openssh-server
    RUN mkdir /var/run/sshd
    RUN echo 'root:root' | chpasswd
    RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
    # SSH login fix. Otherwise user is kicked off after login
    RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
    ENV NOTVISIBLE "in users profile"
    RUN echo "export VISIBLE=now" >> /etc/profile

    EXPOSE 22
    CMD ["/usr/sbin/sshd", "-D"]

    # Directories
    ENV SCRIPTS_DIR /home/scripts
    ENV PKG_DIR /home/pkg
    ENV BASE_DIR /home/workspace
    ENV LEP_REPO_URL https://github.com/DanBloomberg/leptonica.git
    ENV LEP_SRC_DIR ${BASE_DIR}/leptonica
    ENV TES_REPO_URL https://github.com/tesseract-ocr/tesseract.git
    ENV TES_SRC_DIR ${BASE_DIR}/tesseract
    ENV TESSDATA_PREFIX /usr/local/share/tessdata

    RUN mkdir ${SCRIPTS_DIR}
    RUN mkdir ${PKG_DIR}
    RUN mkdir ${BASE_DIR}
    RUN mkdir ${TESSDATA_PREFIX}

    COPY ./container-scripts/* ${SCRIPTS_DIR}/
    RUN chmod +x ${SCRIPTS_DIR}/*
    RUN ${SCRIPTS_DIR}/repos_clone.sh
    RUN ${SCRIPTS_DIR}/tessdata_download.sh

    RUN groupadd -r tesseract && useradd -r -g tesseract tesseract
    USER tesseract

    FROM iron/ruby

    WORKDIR /app

    ADD . /app
    ADD ./bin/textcleaner /usr/local/bin

    ENTRYPOINT ["ruby", "app.rb"]`

my app looks like this:

` 
require 'sinatra'
require 'fileutils'
require "carrierwave"
require 'carrierwave/datamapper'
require "carrierwave/orm/activerecord"
require_relative 'models/image'
require_relative 'data_mapper_setup'

set :protection, except: [ :json_csrf ]

port = ENV['PORT'] || 8080
puts "STARTING SINATRA on port #{port}"
set :port, port
set :bind, '0.0.0.0'

CarrierWave.configure do |config|
  config.root = File.dirname(__FILE__)
end

get '/' do
  ({"Hello" => "World!"}).to_json
end

post '/extractText' do
  begin
    path = File.dirname(__FILE__)
    billID = params[:billID]
    image = Image.new(file: params[:file])
    file = File.new("#{path}#{image.file.url}")
    system("tesseract #{file} --psm 6 resultsFile.txt")
    results = File.read("resultsFile.txt")
  rescue
    status 402
    return "Error reading image"
  end
  status 200
  return resultsFile.to_json
end
`

The line where i get the error at after passing the file is `system("tesseract #{file} --psm 6 resultsFile.txt")`

Any help would be great

**Comment by wildloop** [comment]
The purpose of this container is to compile Tesseract 4. Why don't you use Teserract 4 Runtime Environment container: [tesseractshadow/tesseract4re](https://hub.docker.com/r/tesseractshadow/tesseract4re/)?

**Comment by wrumble** [comment]
Great thanks

**Comment by opyate** [comment]
@wildloop 
> The purpose of this container is to compile Tesseract 4

Please specify somewhere which order the scripts in `container-scripts/` have to be called in.

**Comment by wildloop** [comment]
@opyate Here is the steps info:
https://github.com/tesseract-shadow/tesseract-ocr-compilation/blob/master/README.md#compilation
