### ISSUE TITLE
Newbie question....

### ISSUE THREAD

**Issue by Micharius** [tesseract-shadow/tesseract-ocr-compilation#10]
Hello!
I have a virtual machine (Hyper-V) with Lubuntu installed:
(Ubuntu 21.10 "impisb" base).
I installed Docker an run scripts 1 to 6. I can do the OCR test (although I had to modify the script _6-test-ocr.sh_ , _phototest.tif_ is not available anymore at the location specified in the script).
But I cannot connect to SSH / localhost at port 4022. If I understand right, it should be user _root_ and passwort _root_ but this connection is always refused. What could be the reason?
Kind regards,
Micha

**Comment by kinjelom** [comment]
The root password is here: https://github.com/tesseract-shadow/tesseract-ocr-compilation/blob/fb93548e4ec756bda3dbc0237f58c23053441953/Dockerfile#L41 (currently `troubl3tim3`).

> phototest.tif is not available anymore at the location specified in the script

fixed

Try connect to `127.0.0.1:4022`, or `docker exec -it t4cmp /bin/bash -c "your command"` https://docs.docker.com/engine/reference/commandline/exec/

**Comment by Micharius** [comment]
Thanks! I'll check it out!
