### ISSUE TITLE
SSH into the container is exposed to the world

### ISSUE THREAD

**Issue by geniass** [tesseract-shadow/tesseract-ocr-compilation#2]
@wildloop 

Because the Dockerfile runs `EXPOSE 22` and Docker automatically modifies firewall rules, running this container means **SSH gets exposed on your public IP.** 

The Dockerfile also enables **root login over SSH** (bad) and sets the **root password to `root`** (quite bad) 🤦

I recently left this running over night, and in the morning I found out that someone was mining Monero on my machine.

Is SSH really necessary? Why can't we just use `docker exec` instead?

**Comment by wildloop** [comment]
This container is for quick/convenient/one-time compile, solve problems & forget...
Maybe you are looking for runtime: https://github.com/tesseract-shadow/tesseract-ocr-re

**Comment by geniass** [comment]
I understand its for compilation only. The problem is that compiling everything takes a long time on my machine, and for the whole duration of the compilation process, anyone can port scan my machine and SSH into the container.

**Comment by wildloop** [comment]
Now better: https://github.com/tesseract-shadow/tesseract-ocr-compilation/commit/d9c4c2141e8ff0e1dc2941a498784d6cb86a2eec ?
