### ISSUE TITLE
Running update script breaks compilation

### ISSUE THREAD

**Issue by Chanonry** [tesseract-shadow/tesseract-ocr-compilation#3]
With error:

libtool:   error: REVISION '00' must be a nonnegative integer
libtool:   error: '4:00' is not valid version information

**Comment by wildloop** [comment]
It's work for me: https://hub.docker.com/r/tesseractshadow/tesseract4cmp/builds/byduzskmmpbeejha8rj3mk7/

**Comment by wildloop** [comment]
Please reopen if problem still exists.
